List<Map<String, String>> artist = [
  {'singer': "2ne1", 'image': "singer/artist_2ne1.png"},
  {'singer': "2pm", 'image': "singer/artist_2pm.png"},
  {'singer': "4minute", 'image': "singer/artist_4minute.jpg"},
  {'singer': "24k", 'image': "singer/artist_24k.jpg"},
  {'singer': "ailee", 'image': "singer/artist_ailee.jpg"},
  {'singer': "aoa", 'image': "singer/artist_aoa.jpg"},
  {'singer': "apink", 'image': "singer/artist_apink.jpg"},
  {'singer': "astro", 'image': "singer/artist_astro.jpg"},
  {'singer': "b.a.p", 'image': "singer/artist_bap.jpg"},
  {'singer': "b1a4", 'image': "singer/artist_b1a4.jpg"},
  {'singer': "beast", 'image': "singer/artist_beast.jpg"},
  {'singer': "big bang", 'image': "singer/artist_bigbang.jpg"},
  {'singer': "black pink", 'image': "singer/artist_blackpink.png"},
  {'singer': "block b", 'image': "singer/artist_blockb.jpg"},
  {'singer': "boyfriend", 'image': "singer/artist_boyfriend.jpg"},
  {'singer': "btob", 'image': "singer/artist_btob.jpg"},
  {'singer': "bts", 'image': "singer/artist_bts.jpg"},
  {'singer': "cnblue", 'image': "singer/artist_cnblue.jpg"},
  {'singer': "day6", 'image': "singer/artist_day6.jpg"},
  {'singer': "exid", 'image': "singer/artist_exid.jpg"},
  {'singer': "exo", 'image': "singer/artist_exo.jpg"},
  {'singer': "f(x)", 'image': "singer/artist_fx.jpg"},
  {'singer': "ft island", 'image': "singer/artist_ftisland.jpg"},
  {'singer': "g-dragon", 'image': "singer/artist_gdragon.jpg"},
  {'singer': "girl`s day", 'image': "singer/artist_girlsday.jpg"},
  {'singer': "got7", 'image': "singer/artist_got7.png"},
  {'singer': "gfriend", 'image': "singer/artist_gfriend.jpg"},
  {'singer': "i.u", 'image': "singer/artist_iu.jpg"},
  {'singer': "ikon", 'image': "singer/artist_ikon.jpg"},
  {'singer': "infinite", 'image': "singer/artist_infinite.jpg"},
  {'singer': "ioi", 'image': "singer/artist_ioi.jpg"},
  {'singer': "kard", 'image': "singer/artist_kard.jpg"},
  {'singer': "knk", 'image': "singer/artist_knk.jpg"},
  {'singer': "lovelyz", 'image': "singer/artist_lovelyz.jpg"},
  {'singer': "mamamoo", 'image': "singer/artist_mamamoo.png"},
  {'singer': "miss a", 'image': "singer/artist_missa.jpg"},
  {'singer': "monsta x", 'image': "singer/artist_monstax.jpg"},
  {'singer': "nct", 'image': "singer/artist_nct.jpg"},
  {'singer': "nuest", 'image': "singer/artist_nuest.jpg"},
  {'singer': "oh my girl", 'image': "singer/artist_ohmygirl.jpg"},
  {'singer': "pentagon", 'image': "singer/artist_pentagon.jpg"},
  {'singer': "red velvet", 'image': "singer/artist_redvelvet.jpg"},
  {'singer': "seventeen", 'image': "singer/artist_seventeen.jpg"},
  {'singer': "sf9", 'image': "singer/artist_sf9.jpg"},
  {'singer': "shinee", 'image': "singer/artist_shinee.jpg"},
  {'singer': "sistar", 'image': "singer/artist_sistar.jpg"},
  {'singer': "snsd", 'image': "singer/artist_snsd.jpg"},
  {'singer': "super junior", 'image': "singer/artist_superjunior.jpg"},
  {'singer': "taeyang", 'image': "singer/artist_taeyang.jpg"},
  {'singer': "t-ara", 'image': "singer/artist_tara.jpg"},
  {'singer': "teentop", 'image': "singer/artist_teentop.jpg"},
  {'singer': "twice", 'image': "singer/artist_twice.jpg"},
  {'singer': "u-kiss", 'image': "singer/artist_ukiss.jpg"},
  {'singer': "up10tion", 'image': "singer/artist_up10tion.jpg"},
  {'singer': "vixx", 'image': "singer/artist_vixx.jpg"},
  {'singer': "wanna one", 'image': "singer/artist_wannaone.jpg"},
  {'singer': "winner", 'image': "singer/artist_winner.jpg"},
];
